### ISSUE TITLE
Tweets containing only a photo and #sd5 are not deleted

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [mboggie/selfdestruct#4]
...much to my chagrin
![screen shot 2015-03-06 at 3 00 23 pm](https://cloud.githubusercontent.com/assets/407323/6535255/a5062de8-c411-11e4-9e27-55f12cf565e9.png)

**Comment by mboggie** [comment]
Don't suppose you saved a tweet id, huh?

**Comment by mboggie** [comment]
Was testing for presence of #sd incorrectly. Fixed in commit above.
